/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Pertemuan12;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.swing.JOptionPane;

public class InsertDATAROTI extends javax.swing.JDialog {

    private EntityManagerFactory emf;
    private EntityManager em;

    public void connect() {
        try {
            emf = Persistence.createEntityManagerFactory("PERTEMUAN14PU");
            em = emf.createEntityManager();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi gagal: " + e.getMessage());
        }
    }

    public InsertDATAROTI(Tampilan parent, boolean modal) {
        super(parent, modal);
        initComponents();
        connect();
    }

    public void bersih() {
        textidroti.setText("");
        textnamaroti.setText("");
        textharga.setText("");
        textstok.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textidroti = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textnamaroti = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textharga = new javax.swing.JTextField();
        textstok = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonSIMPAN = new javax.swing.JButton();
        jButtonBATAL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        textidroti.setBackground(new java.awt.Color(255, 255, 255));
        textidroti.setForeground(new java.awt.Color(0, 0, 0));
        textidroti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textidrotiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Id Roti");

        jLabel2.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nama Roti");

        textnamaroti.setBackground(new java.awt.Color(255, 255, 255));
        textnamaroti.setForeground(new java.awt.Color(0, 0, 0));
        textnamaroti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnamarotiActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Harga");

        textharga.setBackground(new java.awt.Color(255, 255, 255));
        textharga.setForeground(new java.awt.Color(0, 0, 0));
        textharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texthargaActionPerformed(evt);
            }
        });

        textstok.setBackground(new java.awt.Color(255, 255, 255));
        textstok.setForeground(new java.awt.Color(0, 0, 0));
        textstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textstokActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Stok");

        jLabel5.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 0));
        jLabel5.setText("TAMBAH DATA ROTI");

        jButtonSIMPAN.setBackground(new java.awt.Color(255, 153, 102));
        jButtonSIMPAN.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonSIMPAN.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSIMPAN.setText("SIMPAN");
        jButtonSIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSIMPANActionPerformed(evt);
            }
        });

        jButtonBATAL.setBackground(new java.awt.Color(255, 153, 102));
        jButtonBATAL.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonBATAL.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBATAL.setText("BATAL");
        jButtonBATAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBATALActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3))
                                        .addGap(30, 30, 30)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                .addComponent(textidroti, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonBATAL)
                                        .addGap(36, 36, 36)
                                        .addComponent(jButtonSIMPAN))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textharga, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                        .addComponent(textstok, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                        .addComponent(textnamaroti, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textidroti, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textnamaroti, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textharga, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textstok, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBATAL)
                    .addComponent(jButtonSIMPAN))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texthargaActionPerformed

    private void textstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textstokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textstokActionPerformed

    private void jButtonSIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSIMPANActionPerformed
        try {
            if (textidroti.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Isi ID Roti !");
            } else if (textnamaroti.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Isi Nama Roti !");
            } else if (textharga.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Isi Harga !");
            } else if (textstok.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Isi Stock !");
            } else {

                EntityManager em = emf.createEntityManager();
                em.getTransaction().begin();

                DataRoti pst = new DataRoti();
                pst.setIdRoti(textidroti.getText());
                pst.setNamaRoti(textnamaroti.getText());
                pst.setHarga(Integer.parseInt(textharga.getText()));
                pst.setStok(Integer.parseInt(textstok.getText()));

                em.persist(pst);
                em.getTransaction().commit();

                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");

                bersih();
                dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Simpan gagal: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonSIMPANActionPerformed

    private void jButtonBATALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBATALActionPerformed
        bersih();
    }//GEN-LAST:event_jButtonBATALActionPerformed

    private void textnamarotiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnamarotiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textnamarotiActionPerformed

    private void textidrotiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textidrotiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textidrotiActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                Insert dialog = new Insert(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBATAL;
    private javax.swing.JButton jButtonSIMPAN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textharga;
    private javax.swing.JTextField textidroti;
    private javax.swing.JTextField textnamaroti;
    private javax.swing.JTextField textstok;
    // End of variables declaration//GEN-END:variables
}
