/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Pertemuan12;

import Pertemuan12.DataRoti;
import Pertemuan12.Pelanggan;
import Pertemuan12.Transaksi;
import static java.nio.file.Files.list;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import static java.util.Collections.list;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.swing.JOptionPane;

public class InsertTRANSAKSI extends javax.swing.JDialog {

    private EntityManagerFactory emf;
    private EntityManager em;
    private Tampilan parent;

    public InsertTRANSAKSI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        connect();
        isiComboBoxPelanggan();
        isiComboBoxRoti();
        this.parent = (Tampilan) parent;

        textidTRANSAKSI.setText(autoID());
        textTANGGAL.setText(java.time.LocalDate.now().toString()); // y
    }

    public void connect() {
        try {
            emf = Persistence.createEntityManagerFactory("PERTEMUAN14PU");
            em = emf.createEntityManager();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi gagal: " + e.getMessage());
        }
    }

    public void isiComboBoxPelanggan() {
        List<Pelanggan> listpelanggan = em.createNamedQuery("Pelanggan.findAll", Pelanggan.class).getResultList();

        jComboBoxNAMAPELANGGAN.removeAllItems();
        jComboBoxNAMAPELANGGAN.addItem(null);  // tampilkan kosong dulu

        for (Pelanggan p : listpelanggan) {
            jComboBoxNAMAPELANGGAN.addItem(p);
        }
    }

    public void isiComboBoxRoti() {
        List<DataRoti> listRoti = em.createNamedQuery("DataRoti.findAll", DataRoti.class).getResultList();

        jComboBoxNAMAROTI.removeAllItems();
        jComboBoxNAMAROTI.addItem(null);  // tampilkan kosong dulu

        for (DataRoti r : listRoti) {
            jComboBoxNAMAROTI.addItem(r);
        }
    }

    private void setTanggalHariIni() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        textTANGGAL.setText(sdf.format(new Date()));
    }

    public String autoID() {
        String id = "T001";

        String sql = "SELECT t.idTransaksi FROM Transaksi t ORDER BY t.idTransaksi DESC";
        List<String> hasil = em.createQuery(sql, String.class).setMaxResults(1).getResultList();

        if (!hasil.isEmpty()) {
            String last = hasil.get(0).substring(1);
            int nomor = Integer.parseInt(last) + 1;
            id = "T" + String.format("%03d", nomor);
        }
        return id;
    }

    private void hitungTotalOtomatis() {
        try {
            DataRoti r = (DataRoti) jComboBoxNAMAROTI.getSelectedItem();
            if (r == null) {
                return;
            }

            if (textJUMLAHBELI.getText().trim().isEmpty()) {
                textTOTAL.setText("");
                return;
            }

            int jumlah = Integer.parseInt(textJUMLAHBELI.getText());
            int total = jumlah * r.getHarga();
            textTOTAL.setText(String.valueOf(total));

        } catch (Exception e) {
            textTOTAL.setText("");
        }
    }

    public void bersih() {
        textidTRANSAKSI.setText("");
        textTANGGAL.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textidTRANSAKSI = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textJUMLAHBELI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonSIMPAN = new javax.swing.JButton();
        jButtonBATAL = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxNAMAPELANGGAN = new javax.swing.JComboBox();
        jComboBoxNAMAROTI = new javax.swing.JComboBox();
        jButtonTOTAL = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        textTOTAL = new javax.swing.JTextField();
        textTANGGAL = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        textidTRANSAKSI.setBackground(new java.awt.Color(255, 255, 255));
        textidTRANSAKSI.setForeground(new java.awt.Color(0, 0, 0));
        textidTRANSAKSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textidTRANSAKSIActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Id Transaksi");

        jLabel2.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tanggal");

        jLabel3.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Jumlah beli");

        textJUMLAHBELI.setBackground(new java.awt.Color(255, 255, 255));
        textJUMLAHBELI.setForeground(new java.awt.Color(0, 0, 0));
        textJUMLAHBELI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textJUMLAHBELIActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nama Pelanggan");

        jLabel5.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 0));
        jLabel5.setText("TAMBAH TRANSAKSI");

        jButtonSIMPAN.setBackground(new java.awt.Color(255, 153, 102));
        jButtonSIMPAN.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonSIMPAN.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSIMPAN.setText("SIMPAN");
        jButtonSIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSIMPANActionPerformed(evt);
            }
        });

        jButtonBATAL.setBackground(new java.awt.Color(255, 153, 102));
        jButtonBATAL.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonBATAL.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBATAL.setText("BATAL");
        jButtonBATAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBATALActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nama Roti");

        jComboBoxNAMAPELANGGAN.setBackground(new java.awt.Color(255, 153, 51));
        jComboBoxNAMAPELANGGAN.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxNAMAPELANGGAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNAMAPELANGGANActionPerformed(evt);
            }
        });

        jComboBoxNAMAROTI.setBackground(new java.awt.Color(255, 153, 0));
        jComboBoxNAMAROTI.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxNAMAROTI.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jComboBoxNAMAROTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNAMAROTIActionPerformed(evt);
            }
        });

        jButtonTOTAL.setBackground(new java.awt.Color(255, 153, 102));
        jButtonTOTAL.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonTOTAL.setForeground(new java.awt.Color(0, 0, 0));
        jButtonTOTAL.setText("TOTAL");
        jButtonTOTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTOTALActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("TOTAL");

        textTOTAL.setBackground(new java.awt.Color(255, 204, 153));
        textTOTAL.setForeground(new java.awt.Color(0, 0, 0));
        textTOTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTOTALActionPerformed(evt);
            }
        });

        textTANGGAL.setBackground(new java.awt.Color(255, 255, 255));
        textTANGGAL.setForeground(new java.awt.Color(0, 0, 0));
        textTANGGAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTANGGALActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 151, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(137, 137, 137))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonBATAL)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonSIMPAN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textJUMLAHBELI, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .addComponent(jComboBoxNAMAPELANGGAN, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxNAMAROTI, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textTOTAL, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .addComponent(textTANGGAL)
                            .addComponent(textidTRANSAKSI))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonTOTAL)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textidTRANSAKSI, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTANGGAL, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(textJUMLAHBELI, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxNAMAPELANGGAN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxNAMAROTI, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTOTAL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSIMPAN)
                    .addComponent(jButtonBATAL))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textJUMLAHBELIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textJUMLAHBELIActionPerformed
        hitungTotalOtomatis();
    }//GEN-LAST:event_textJUMLAHBELIActionPerformed

    private void jButtonSIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSIMPANActionPerformed

        if (textidTRANSAKSI.getText().trim().isEmpty()
                || textTANGGAL.getText().trim().isEmpty()
                || textJUMLAHBELI.getText().trim().isEmpty()
                || textTOTAL.getText().trim().isEmpty()
                || jComboBoxNAMAPELANGGAN.getSelectedItem() == null
                || jComboBoxNAMAROTI.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this,
                    "Total belum dihitung! Mohon isi jumlah atau pilih roti.");
            return;
        }

        int jumlahBeli;
        try {
            jumlahBeli = Integer.parseInt(textJUMLAHBELI.getText().trim());
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Jumlah beli harus berupa angka.");
            textJUMLAHBELI.requestFocus();
            return;
        }

        int totalHarga;
        try {
            totalHarga = Integer.parseInt(textTOTAL.getText().trim());
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Total harga tidak valid.");
            textTOTAL.requestFocus();
            return;
        }

        // Parsing tanggal
        java.sql.Date sqlDate = null;
        String tanggalInput = textTANGGAL.getText().trim();

        DateTimeFormatter[] formatters = new DateTimeFormatter[]{
            DateTimeFormatter.ofPattern("yyyy-MM-dd"),
            DateTimeFormatter.ofPattern("dd-MM-yyyy"),
            DateTimeFormatter.ofPattern("dd/MM/yyyy"),
            DateTimeFormatter.ofPattern("dd MMMM yyyy", new Locale("id", "ID")),
            DateTimeFormatter.ofPattern("dd MMM yyyy", new Locale("id", "ID"))
        };

        java.time.LocalDate parsedLocalDate = null;
        boolean tanggalParsed = false;
        for (DateTimeFormatter fmt : formatters) {
            try {
                parsedLocalDate = java.time.LocalDate.parse(tanggalInput, fmt);
                tanggalParsed = true;
                break;
            } catch (Exception e) {
            }
        }

        if (!tanggalParsed) {
            JOptionPane.showMessageDialog(this,
                    "Format tanggal salah!\nGunakan salah satu format:\n"
                    + "yyyy-MM-dd\n"
                    + "dd-MM-yyyy\n"
                    + "dd/MM/yyyy\n"
                    + "dd MMMM yyyy",
                    "Format Tanggal Salah",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        sqlDate = java.sql.Date.valueOf(parsedLocalDate);

        String idTransaksi = textidTRANSAKSI.getText().trim();
        if (idTransaksi.equals("")) {
            idTransaksi = autoID();
        }

        EntityManager emLocal = null;
        try {
            emLocal = emf.createEntityManager();
            emLocal.getTransaction().begin();

            Transaksi t = new Transaksi();
            t.setIdTransaksi(idTransaksi);
            t.setTanggal(sqlDate);
            t.setJumlahBeli(jumlahBeli);
            t.setTotalHarga(totalHarga);

            Pelanggan p = (Pelanggan) jComboBoxNAMAPELANGGAN.getSelectedItem();
            t.setIdPelanggan(p);

            DataRoti r = (DataRoti) jComboBoxNAMAROTI.getSelectedItem();
            t.setIdRoti(r);

            emLocal.persist(t);
            emLocal.getTransaction().commit();

            JOptionPane.showMessageDialog(this, "Transaksi berhasil disimpan!");

            bersih();
            dispose();

        } catch (Exception e) {
            if (emLocal != null && emLocal.getTransaction().isActive()) {
                emLocal.getTransaction().rollback();
            }
            JOptionPane.showMessageDialog(this,
                    "Error saat menyimpan transaksi: " + e.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE);
        } finally {
            if (emLocal != null && emLocal.isOpen()) {
                emLocal.close();
            }
        }
    }//GEN-LAST:event_jButtonSIMPANActionPerformed

    private void jButtonBATALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBATALActionPerformed
        bersih();
    }//GEN-LAST:event_jButtonBATALActionPerformed

    private void textidTRANSAKSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textidTRANSAKSIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textidTRANSAKSIActionPerformed

    private void jButtonTOTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTOTALActionPerformed
        try {

            DataRoti r = (DataRoti) jComboBoxNAMAROTI.getSelectedItem();

            if (r == null) {
                JOptionPane.showMessageDialog(this, "Pilih roti terlebih dahulu!");
                return;
            }

            if (textJUMLAHBELI.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Masukkan jumlah beli dulu!");
                return;
            }

            int jumlah = Integer.parseInt(textJUMLAHBELI.getText());

            int total = jumlah * r.getHarga();

            textTOTAL.setText(String.valueOf(total));

            JOptionPane.showMessageDialog(this,
                    "Total harga kamu: Rp " + total);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Jumlah beli harus berupa angka!",
                    "Input Error",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Terjadi kesalahan: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonTOTALActionPerformed

    private void textTOTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTOTALActionPerformed
        hitungTotalOtomatis();
    }//GEN-LAST:event_textTOTALActionPerformed

    private void jComboBoxNAMAPELANGGANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNAMAPELANGGANActionPerformed

    }//GEN-LAST:event_jComboBoxNAMAPELANGGANActionPerformed

    private void jComboBoxNAMAROTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNAMAROTIActionPerformed
        hitungTotalOtomatis();
    }//GEN-LAST:event_jComboBoxNAMAROTIActionPerformed

    private void textTANGGALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTANGGALActionPerformed

    }//GEN-LAST:event_textTANGGALActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                Insert dialog = new Insert(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBATAL;
    private javax.swing.JButton jButtonSIMPAN;
    private javax.swing.JButton jButtonTOTAL;
    private javax.swing.JComboBox jComboBoxNAMAPELANGGAN;
    private javax.swing.JComboBox jComboBoxNAMAROTI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textJUMLAHBELI;
    private javax.swing.JTextField textTANGGAL;
    private javax.swing.JTextField textTOTAL;
    private javax.swing.JTextField textidTRANSAKSI;
    // End of variables declaration//GEN-END:variables
}
