/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Pertemuan12;

import java.awt.Frame;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class UpdateDATAROTI extends javax.swing.JDialog {

    private EntityManagerFactory emf;
    private EntityManager em;

    public void connect() {
        try {
            emf = Persistence.createEntityManagerFactory("PERTEMUAN14PU");
            em = emf.createEntityManager();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi gagal: " + e.getMessage());
        }
    }

    String idrotiLama, namarotiLama, hargaLama, stokLama, idpelangganLama;

    /**
     * Creates new form Update
     */
    public UpdateDATAROTI(Frame parent, boolean modal,
            String idrotiLama, String namarotiLama,
            String hargaLama, String stokLama, String idpelangganLama) {

        super(parent, modal);
        initComponents();
        connect();
        isicomboboxPELANGGAN();

        this.idrotiLama = idrotiLama;
        this.namarotiLama = namarotiLama;
        this.hargaLama = hargaLama;
        this.stokLama = stokLama;
        this.idpelangganLama = idpelangganLama;

        textidroti.setText(idrotiLama);
        textnamaroti.setText(namarotiLama);
        textharga.setText(hargaLama);
        textstok.setText(stokLama);

        for (int i = 0; i < jComboBoxIDPELANGGAN.getItemCount(); i++) {
            Pelanggan p = jComboBoxIDPELANGGAN.getItemAt(i);
            if (p.getNamaPelanggan().equals(idpelangganLama)) {
                jComboBoxIDPELANGGAN.setSelectedIndex(i);
                break;
            }
        }
    }

    public void bersih() {
        textidroti.setText("");
        textnamaroti.setText("");
        textharga.setText("");
        textstok.setText("");
        jComboBoxIDPELANGGAN.setSelectedIndex(-1);
    }

    private void isicomboboxPELANGGAN() {
        EntityManager em = emf.createEntityManager();
        try {
            TypedQuery<Pelanggan> query = em.createQuery("SELECT p FROM Pelanggan p", Pelanggan.class);

            List<Pelanggan> hasil = query.getResultList();

            if (!hasil.isEmpty()) {
                for (Pelanggan p : hasil) {
                    jComboBoxIDPELANGGAN.addItem(p);
                }
            }

        } finally {
            em.close();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        textidroti = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textnamaroti = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textharga = new javax.swing.JTextField();
        textstok = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonPERBARUI = new javax.swing.JButton();
        jButtonBATAL = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxIDPELANGGAN = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        textidroti.setBackground(new java.awt.Color(255, 255, 255));
        textidroti.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Id Roti");

        jLabel2.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nama Roti");

        textnamaroti.setBackground(new java.awt.Color(255, 255, 255));
        textnamaroti.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Harga");

        textharga.setBackground(new java.awt.Color(255, 255, 255));
        textharga.setForeground(new java.awt.Color(0, 0, 0));
        textharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texthargaActionPerformed(evt);
            }
        });

        textstok.setBackground(new java.awt.Color(255, 255, 255));
        textstok.setForeground(new java.awt.Color(0, 0, 0));
        textstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textstokActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Stok");

        jLabel5.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 0));
        jLabel5.setText("PERBARUI DATA ROTI");

        jButtonPERBARUI.setBackground(new java.awt.Color(255, 102, 51));
        jButtonPERBARUI.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPERBARUI.setForeground(new java.awt.Color(0, 0, 0));
        jButtonPERBARUI.setText("PERBARUI");
        jButtonPERBARUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPERBARUIActionPerformed(evt);
            }
        });

        jButtonBATAL.setBackground(new java.awt.Color(255, 102, 51));
        jButtonBATAL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonBATAL.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBATAL.setText("BATAL");
        jButtonBATAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBATALActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nama Pelanggan");

        jComboBoxIDPELANGGAN.setBackground(new java.awt.Color(255, 204, 153));
        jComboBoxIDPELANGGAN.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxIDPELANGGAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIDPELANGGANActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonBATAL)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPERBARUI)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textharga, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(textidroti, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(textnamaroti, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(textstok, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(jComboBoxIDPELANGGAN, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textidroti, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textnamaroti, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(textharga, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textstok, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxIDPELANGGAN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPERBARUI)
                    .addComponent(jButtonBATAL))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texthargaActionPerformed

    private void textstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textstokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textstokActionPerformed

    private void jButtonPERBARUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPERBARUIActionPerformed
        if (textidroti.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Isi Semua Data!");
        } else if (textnamaroti.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Isi Semua Data!");
        } else if (textharga.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Isi Semua Data!");
        } else if (textstok.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Isi Semua Data!");
        } else if (jComboBoxIDPELANGGAN.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Isi Semua Data!");
        } else {
            try {
                EntityManager em = emf.createEntityManager();
                em.getTransaction().begin();

                TypedQuery<DataRoti> query = em.createQuery(
                        "SELECT d FROM DataRoti d WHERE d.idRoti = :idRoti ", DataRoti.class);

                query.setParameter("idRoti", idrotiLama);
                List<DataRoti> hasil = query.getResultList();

                if (!hasil.isEmpty()) {
                    DataRoti roti = hasil.get(0);

                    roti.setIdRoti(textidroti.getText());
                    roti.setNamaRoti(textnamaroti.getText());
                    roti.setHarga(Integer.parseInt(textharga.getText()));
                    roti.setStok(Integer.parseInt(textstok.getText()));

                    Pelanggan p = (Pelanggan) jComboBoxIDPELANGGAN.getSelectedItem();
                    roti.setIdPelanggan(p);

                    em.merge(roti);
                    em.getTransaction().commit();

                    JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Data tidak ditemukan!");
                }

                em.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }

    }//GEN-LAST:event_jButtonPERBARUIActionPerformed

    private void jButtonBATALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBATALActionPerformed
        bersih();
    }//GEN-LAST:event_jButtonBATALActionPerformed

    private void jComboBoxIDPELANGGANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIDPELANGGANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxIDPELANGGANActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                Update dialog = new Update(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBATAL;
    private javax.swing.JButton jButtonPERBARUI;
    private javax.swing.JComboBox<Pelanggan> jComboBoxIDPELANGGAN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField textharga;
    private javax.swing.JTextField textidroti;
    private javax.swing.JTextField textnamaroti;
    private javax.swing.JTextField textstok;
    // End of variables declaration//GEN-END:variables
}
