/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Pertemuan12;

import Pertemuan12.DataRoti;
import Pertemuan12.Pelanggan;
import Pertemuan12.Transaksi;
import java.awt.Frame;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author HP
 */
public class UpdateTRANSAKSI extends javax.swing.JDialog {

    private EntityManagerFactory emf;
    private EntityManager em;

    private String idTransaksiLama;
    private String idrotiLama;
    private String idpelangganLama;
    private String jumlahLama;
    private String totalLama;
    private String tanggalLama;

    private Transaksi t;
    private final SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

    public UpdateTRANSAKSI(
            Frame parent,
            boolean modal,
            String idTransaksi,
            String tanggal,
            String jumlah,
            String idPelanggan,
            String idRoti,
            String total) {

        super(parent, modal);
        initComponents();

        connect();
        isiComboBoxPelanggan();
        isiComboBoxRoti();

        // AMBIL DATA TRANSAKSI DARI DB
        t = em.find(Transaksi.class, idTransaksi);

        if (t == null) {
            JOptionPane.showMessageDialog(this, "Data transaksi tidak ditemukan!");
            dispose();
            return;
        }

        textidTRANSAKSI.setText(t.getIdTransaksi());
        String tanggalFormatted = sdf.format(t.getTanggal());
        textTANGGAL.setText(tanggalFormatted);
        textJUMLAHBELI.setText(String.valueOf(t.getJumlahBeli()));
        textTOTAL.setText(String.valueOf(t.getTotalHarga()));

        jComboBoxNAMAPELANGGAN.setSelectedItem(t.getIdPelanggan());
        jComboBoxNAMAROTI.setSelectedItem(t.getIdRoti());
    }

    private void setSelectedComboRoti(String idRoti) {
        for (int i = 0; i < jComboBoxNAMAROTI.getItemCount(); i++) {
            String r = jComboBoxNAMAROTI.getItemAt(i).toString();
            if (r.equals(idRoti)) {
                jComboBoxNAMAROTI.setSelectedIndex(i);
                return;
            }
        }
    }

    private void setSelectedComboPelanggan(String idPelanggan) {
        for (int i = 0; i < jComboBoxNAMAPELANGGAN.getItemCount(); i++) {
            String p = jComboBoxNAMAPELANGGAN.getItemAt(i).toString();
            if (p.equals(idPelanggan)) {
                jComboBoxNAMAPELANGGAN.setSelectedIndex(i);
                return;
            }
        }
    }

    public void connect() {
        emf = Persistence.createEntityManagerFactory("PERTEMUAN14PU");
        em = emf.createEntityManager();
    }

    public void isiComboBoxPelanggan() {
        List<Pelanggan> listPelanggan = em.createNamedQuery("Pelanggan.findAll", Pelanggan.class).getResultList();
        jComboBoxNAMAPELANGGAN.removeAllItems();
        for (Pelanggan p : listPelanggan) {
            jComboBoxNAMAPELANGGAN.addItem(p);
        }
    }

    public void isiComboBoxRoti() {
        List<DataRoti> listRoti = em.createNamedQuery("DataRoti.findAll", DataRoti.class).getResultList();
        jComboBoxNAMAROTI.removeAllItems();
        for (DataRoti r : listRoti) {
            jComboBoxNAMAROTI.addItem(r);
        }
    }

    public void hitungTotal() {
        try {
            int jumlah = Integer.parseInt(textJUMLAHBELI.getText());
            DataRoti r = (DataRoti) jComboBoxNAMAROTI.getSelectedItem();
            if (r != null) {
                textTOTAL.setText(String.valueOf(jumlah * r.getHarga()));
            }
        } catch (Exception e) {
            textTOTAL.setText("");
        }
    }

    public void bersih() {
        textidTRANSAKSI.setText("");
        textJUMLAHBELI.setText("");
        textTOTAL.setText("");

        jComboBoxNAMAROTI.setSelectedIndex(-1);
        jComboBoxNAMAPELANGGAN.setSelectedIndex(-1);

        textidTRANSAKSI.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonPERBARUI = new javax.swing.JButton();
        jButtonBATAL = new javax.swing.JButton();
        textidTRANSAKSI = new javax.swing.JTextField();
        textTANGGAL = new javax.swing.JTextField();
        textJUMLAHBELI = new javax.swing.JTextField();
        jComboBoxNAMAPELANGGAN = new javax.swing.JComboBox();
        jComboBoxNAMAROTI = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        textTOTAL = new javax.swing.JTextField();
        jButtonTOTAL = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Id Transaksi");

        jLabel2.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tanggal Pemesanan");

        jLabel3.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Jumlah Beli");

        jLabel4.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nama Pelanggan");

        jLabel5.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 0));
        jLabel5.setText("PERBARUI DATA ROTI");

        jButtonPERBARUI.setBackground(new java.awt.Color(255, 102, 51));
        jButtonPERBARUI.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPERBARUI.setForeground(new java.awt.Color(0, 0, 0));
        jButtonPERBARUI.setText("PERBARUI");
        jButtonPERBARUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPERBARUIActionPerformed(evt);
            }
        });

        jButtonBATAL.setBackground(new java.awt.Color(255, 102, 51));
        jButtonBATAL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonBATAL.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBATAL.setText("BATAL");
        jButtonBATAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBATALActionPerformed(evt);
            }
        });

        textidTRANSAKSI.setBackground(new java.awt.Color(255, 255, 255));
        textidTRANSAKSI.setForeground(new java.awt.Color(0, 0, 0));
        textidTRANSAKSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textidTRANSAKSIActionPerformed(evt);
            }
        });

        textTANGGAL.setBackground(new java.awt.Color(255, 255, 255));
        textTANGGAL.setForeground(new java.awt.Color(0, 0, 0));
        textTANGGAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTANGGALActionPerformed(evt);
            }
        });

        textJUMLAHBELI.setBackground(new java.awt.Color(255, 255, 255));
        textJUMLAHBELI.setForeground(new java.awt.Color(0, 0, 0));
        textJUMLAHBELI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textJUMLAHBELIActionPerformed(evt);
            }
        });

        jComboBoxNAMAPELANGGAN.setBackground(new java.awt.Color(255, 153, 51));
        jComboBoxNAMAPELANGGAN.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxNAMAPELANGGAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNAMAPELANGGANActionPerformed(evt);
            }
        });

        jComboBoxNAMAROTI.setBackground(new java.awt.Color(255, 153, 0));
        jComboBoxNAMAROTI.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxNAMAROTI.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jComboBoxNAMAROTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNAMAROTIActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("TOTAL");

        textTOTAL.setBackground(new java.awt.Color(255, 204, 153));
        textTOTAL.setForeground(new java.awt.Color(0, 0, 0));
        textTOTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTOTALActionPerformed(evt);
            }
        });

        jButtonTOTAL.setBackground(new java.awt.Color(255, 153, 102));
        jButtonTOTAL.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonTOTAL.setForeground(new java.awt.Color(0, 0, 0));
        jButtonTOTAL.setText("TOTAL");

        jLabel7.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nama Roti");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel5)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel6))
                    .addComponent(jLabel7))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonBATAL)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPERBARUI))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxNAMAPELANGGAN, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textidTRANSAKSI)
                                .addComponent(textTANGGAL)
                                .addComponent(textJUMLAHBELI, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                .addComponent(jComboBoxNAMAROTI, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textTOTAL, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonTOTAL)))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textidTRANSAKSI, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textTANGGAL, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textJUMLAHBELI, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxNAMAPELANGGAN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxNAMAROTI, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTOTAL))))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBATAL)
                    .addComponent(jButtonPERBARUI))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPERBARUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPERBARUIActionPerformed
        try {
            em.getTransaction().begin();

            String idTransaksiBaru = textidTRANSAKSI.getText().trim();
            String tanggalStr = textTANGGAL.getText().trim();
            int jumlahBaru = Integer.parseInt(textJUMLAHBELI.getText().trim());
            int totalBaru = Integer.parseInt(textTOTAL.getText().trim());

            // Konversi String tanggal → Date
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date tanggalDate = sdf.parse(tanggalStr);

            DataRoti rotiBaru = (DataRoti) jComboBoxNAMAROTI.getSelectedItem();
            Pelanggan pelangganBaru = (Pelanggan) jComboBoxNAMAPELANGGAN.getSelectedItem();

            // SET NILAI KE OBJEK TRANSAKSI
            t.setIdTransaksi(idTransaksiBaru);
            t.setTanggal(tanggalDate);     // ✔ SUDAH BENAR (Date)
            t.setJumlahBeli(jumlahBaru);
            t.setTotalHarga(totalBaru);
            t.setIdRoti(rotiBaru);
            t.setIdPelanggan(pelangganBaru);

            em.merge(t);
            em.getTransaction().commit();

            JOptionPane.showMessageDialog(this, "Data transaksi berhasil diperbarui!");
            dispose();

        } catch (Exception e) {
            em.getTransaction().rollback();
            JOptionPane.showMessageDialog(this, "Gagal memperbarui transaksi: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonPERBARUIActionPerformed

    private void jButtonBATALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBATALActionPerformed
        bersih();
    }//GEN-LAST:event_jButtonBATALActionPerformed

    private void textidTRANSAKSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textidTRANSAKSIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textidTRANSAKSIActionPerformed

    private void textTANGGALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTANGGALActionPerformed

    }//GEN-LAST:event_textTANGGALActionPerformed

    private void textJUMLAHBELIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textJUMLAHBELIActionPerformed
        hitungTotal();
    }//GEN-LAST:event_textJUMLAHBELIActionPerformed

    private void jComboBoxNAMAPELANGGANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNAMAPELANGGANActionPerformed

    }//GEN-LAST:event_jComboBoxNAMAPELANGGANActionPerformed

    private void jComboBoxNAMAROTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNAMAROTIActionPerformed
        hitungTotal();
    }//GEN-LAST:event_jComboBoxNAMAROTIActionPerformed

    private void textTOTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTOTALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTOTALActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                Update dialog = new Update(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBATAL;
    private javax.swing.JButton jButtonPERBARUI;
    private javax.swing.JButton jButtonTOTAL;
    private javax.swing.JComboBox jComboBoxNAMAPELANGGAN;
    private javax.swing.JComboBox jComboBoxNAMAROTI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField textJUMLAHBELI;
    private javax.swing.JTextField textTANGGAL;
    private javax.swing.JTextField textTOTAL;
    private javax.swing.JTextField textidTRANSAKSI;
    // End of variables declaration//GEN-END:variables
}
