/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pertemuan13;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class LOGIN extends javax.swing.JFrame {

    private BUAT BUAT;
    private UBAH UBAH;

    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldUSER = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonMASUK = new javax.swing.JButton();
        jLabelLUPAPASSWORD = new javax.swing.JLabel();
        jLabelDaftar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPASS = new javax.swing.JPasswordField();
        jCheckBoxPASS = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("LOGIN");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Username");

        jTextFieldUSER.setBackground(new java.awt.Color(255, 204, 153));
        jTextFieldUSER.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldUSER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUSERActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Password");

        jButtonMASUK.setBackground(new java.awt.Color(255, 204, 153));
        jButtonMASUK.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonMASUK.setForeground(new java.awt.Color(0, 0, 0));
        jButtonMASUK.setText("MASUK");
        jButtonMASUK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMASUKActionPerformed(evt);
            }
        });

        jLabelLUPAPASSWORD.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelLUPAPASSWORD.setForeground(new java.awt.Color(0, 0, 0));
        jLabelLUPAPASSWORD.setText("Lupa Password?");
        jLabelLUPAPASSWORD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLUPAPASSWORDMouseClicked(evt);
            }
        });

        jLabelDaftar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelDaftar.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDaftar.setText("Daftar");
        jLabelDaftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDaftarMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Belum punya akun ?");

        jTextFieldPASS.setBackground(new java.awt.Color(255, 204, 153));
        jTextFieldPASS.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldPASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPASSActionPerformed(evt);
            }
        });

        jCheckBoxPASS.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxPASS.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxPASS.setText("Tampilkan kata sandi");
        jCheckBoxPASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPASSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jButtonMASUK))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDaftar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBoxPASS)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldUSER, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jTextFieldPASS, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabelLUPAPASSWORD)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUSER, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPASS, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBoxPASS)
                .addGap(18, 18, 18)
                .addComponent(jLabelLUPAPASSWORD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMASUK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelDaftar))
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMASUKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMASUKActionPerformed
        if (jTextFieldUSER.getText().equals("") | jTextFieldPASS.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Terlebih Dahulu");
        } else {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("PERTEMUAN14PU");
            EntityManager em = emf.createEntityManager();

            em.getTransaction().begin();

            String user = jTextFieldUSER.getText();
            String pw = jTextFieldPASS.getText();
            Akun y = em.find(Akun.class, user);

            if (y == null) {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
                jTextFieldUSER.requestFocus();
            } else if (y.getPassword().equals(pw)) {
                JOptionPane.showMessageDialog(null, "Selamat datang " + user );
                new Pertemuan12.Tampilan().setVisible(true);
             

                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Password salah!");
                jTextFieldPASS.setText("");
                jTextFieldPASS.requestFocus();
            }
            em.getTransaction().commit();
            em.close();
            emf.close();
        }
    }//GEN-LAST:event_jButtonMASUKActionPerformed

    private void jTextFieldUSERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUSERActionPerformed
         if (jTextFieldUSER.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi username dulu!");
        } else {
            jTextFieldPASS.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldUSERActionPerformed

    private void jLabelDaftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDaftarMouseClicked
        BUAT = new BUAT(); // buka form Buat
        BUAT.setVisible(true);  // tampilkan
        this.dispose();
    }//GEN-LAST:event_jLabelDaftarMouseClicked

    private void jLabelLUPAPASSWORDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLUPAPASSWORDMouseClicked
        UBAH = new UBAH(); // buka form Buat
        UBAH.setVisible(true);  // tampilkan
        this.dispose();
    }//GEN-LAST:event_jLabelLUPAPASSWORDMouseClicked

    private void jTextFieldPASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPASSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPASSActionPerformed

    private void jCheckBoxPASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPASSActionPerformed
        if (jCheckBoxPASS.isSelected()) {
            jTextFieldPASS.setEchoChar((char) 0);
        } else {
            jTextFieldPASS.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxPASSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMASUK;
    private javax.swing.JCheckBox jCheckBoxPASS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelDaftar;
    private javax.swing.JLabel jLabelLUPAPASSWORD;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jTextFieldPASS;
    private javax.swing.JTextField jTextFieldUSER;
    // End of variables declaration//GEN-END:variables
}
