/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pertemuan13;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */

public class UBAH extends javax.swing.JFrame {

    /**
     * Creates new form UBAHSALAH2
     */
    public UBAH() {
        initComponents();
        jLabelPASS.setVisible(false);
        jButtonUBAH.setVisible(false);
        jTextFieldPASS.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldUSER = new javax.swing.JTextField();
        jLabelPASS = new javax.swing.JLabel();
        jTextFieldPASS = new javax.swing.JTextField();
        jButtonCARI = new javax.swing.JButton();
        jButtonUBAH = new javax.swing.JButton();
        jLabelBACK = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("UBAH");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Username");

        jTextFieldUSER.setBackground(new java.awt.Color(255, 204, 153));
        jTextFieldUSER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUSERActionPerformed(evt);
            }
        });

        jLabelPASS.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabelPASS.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPASS.setText("Password");

        jTextFieldPASS.setBackground(new java.awt.Color(255, 204, 153));
        jTextFieldPASS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldPASSMouseClicked(evt);
            }
        });
        jTextFieldPASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPASSActionPerformed(evt);
            }
        });

        jButtonCARI.setBackground(new java.awt.Color(255, 204, 153));
        jButtonCARI.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonCARI.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCARI.setText("cari");
        jButtonCARI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCARIActionPerformed(evt);
            }
        });

        jButtonUBAH.setBackground(new java.awt.Color(255, 204, 153));
        jButtonUBAH.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonUBAH.setForeground(new java.awt.Color(0, 0, 0));
        jButtonUBAH.setText("UBAH");
        jButtonUBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUBAHActionPerformed(evt);
            }
        });

        jLabelBACK.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabelBACK.setForeground(new java.awt.Color(0, 0, 0));
        jLabelBACK.setText("<");
        jLabelBACK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBACKMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabelBACK)
                                .addGap(73, 73, 73)
                                .addComponent(jLabel1)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldUSER, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addComponent(jTextFieldPASS, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabelPASS)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jButtonCARI, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jButtonUBAH)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabelBACK))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCARI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldUSER, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPASS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPASS, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jButtonUBAH)
                .addGap(38, 38, 38))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUSERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUSERActionPerformed
        if (jTextFieldUSER.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi username dulu!");
        } else {
            jButtonCARI.doClick();
        }
    }//GEN-LAST:event_jTextFieldUSERActionPerformed

    private void jTextFieldPASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPASSActionPerformed
        jButtonCARI.doClick();
    }//GEN-LAST:event_jTextFieldPASSActionPerformed

    private void jButtonCARIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCARIActionPerformed
        if (jTextFieldUSER.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi username terlebih dahulu");
        } else {
            try {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("PERTEMUAN14PU");
            EntityManager em = emf.createEntityManager();

            em.getTransaction().begin();

            String user = jTextFieldUSER.getText();
            Akun a = em.find(Akun.class, user);
            if (a != null) {
                String inputIbu = JOptionPane.showInputDialog(
                        this,
                        "Username ditemukan! "
                        + "Masukkan Nama Ibu untuk konfirmasi:",
                        "Konfirmasi Keamanan",
                        JOptionPane.QUESTION_MESSAGE
                );

                if (inputIbu == null) {
                    return;
                }

                if (!inputIbu.equalsIgnoreCase(a.getNamaIbu())) {
                    JOptionPane.showMessageDialog(this,
                            "Nama Ibu tidak sesuai!",
                            "Peringatan", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                JOptionPane.showMessageDialog(this,
                        "Verifikasi berhasil! Silahkan ubah password.",
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);

                jLabelPASS.setVisible(true);
                jButtonUBAH.setVisible(true);
                jTextFieldPASS.setVisible(true);
                jTextFieldUSER.setEditable(false);
                jTextFieldPASS.requestFocus();
            } else {
                JOptionPane.showMessageDialog(this,
                        "Username tidak ditemukan!",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }

            em.getTransaction().commit();
        }catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Terjadi kesalahan koneksi: " + e.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
    }
    }//GEN-LAST:event_jButtonCARIActionPerformed

    private void jButtonUBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUBAHActionPerformed
        if (jTextFieldPASS.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi password baru terlebih dahulu");
        } else {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("PERTEMUAN14PU");
            EntityManager em = emf.createEntityManager();

            em.getTransaction().begin();

            String user = jTextFieldUSER.getText();
            Akun y = em.find(Akun.class, user);

            if (y != null) {
                // ubah password
                y.setPassword(jTextFieldPASS.getText());
                em.merge(y);
                em.getTransaction().commit();

                JOptionPane.showMessageDialog(null, "Password berhasil diubah! Silakan login kembali.");

                // tutup form ini, buka form LOGIN
                this.dispose();
                new LOGIN().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Akun tidak ditemukan!");
            }

            em.close();
            emf.close();
        }
    }//GEN-LAST:event_jButtonUBAHActionPerformed

    private void jTextFieldPASSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPASSMouseClicked
        jButtonUBAH.doClick();
    }//GEN-LAST:event_jTextFieldPASSMouseClicked

    private void jLabelBACKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBACKMouseClicked
        LOGIN y = new LOGIN();
        y.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelBACKMouseClicked

    /**
     * @param args the command line arguments
     */
//      }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCARI;
    private javax.swing.JButton jButtonUBAH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBACK;
    private javax.swing.JLabel jLabelPASS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldPASS;
    private javax.swing.JTextField jTextFieldUSER;
    // End of variables declaration//GEN-END:variables
}
